CREATE TABLE postup_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES postup_users(id) ON DELETE SET NULL,
    user_name TEXT NOT NULL,
    comment TEXT,
    game_id INTEGER REFERENCES postup_games(id) ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);

